### ISSUE TITLE
Respect CSS media prefers-color-scheme: dark

### ISSUE THREAD

**Issue by jouni** [vaadin-component-factory/vcf-dark-mode-switch#3]
The component should automatically detect if dark mode should be enabled, if the user has not made an explicit choice about the color mode yet.

Sidenote: it would be great if the user could “reset” the switch to “auto mode” so that the OS level setting (media query) would be respected. Not exactly sure how that could work in the UI.

**Comment by jouni** [comment]
Or, maybe we should use `sessionStorage` instead of `localStorage`? So that in the beginning of each browser session, we respect the OS-level setting, but the user can override that for the duration of the session.

Then I’m wondering how that’ll work with apps installed on the home screen, when do they get a new session?

One more option is to give the value in `localStorage` an expiration time, or somehow else create some heuristics when the value should be cleared.

**Comment by sohrabtaee** [comment]
I would consider this as an extra feature as it's not currently available in TaskMob. We can add these later, at the moment, is there something missing from the original behavior of the component?

**Comment by jouni** [comment]
This is currently available in TaskMob. You can try it on macOS using Safari or the latest Chrome. Try with incognito to avoid the stored value in localStorage.

https://www.dropbox.com/s/ulojzgh0m7pytlf/taskmob-dark-mode.mov?dl=0

It could be a configuration option which the developer can toggle on/off, if some apps don’t want to respect OS-level settings.

**Comment by sohrabtaee** [comment]
Cool! But I guess the UX for auto mode is confusing. What do you think about changing the switch button to a 3-state switch?

**Comment by jouni** [comment]
Yeah, it’s not ideal. But I would not spend time now to redesign and reimplement it. I don’t think I’ve seen a 3-state switch on any site/app that offers a dark mode, so I’m wondering if that would be more difficult for users to understand. This would benefit from a bit of user research.

**Comment by sohrabtaee** [comment]
Fixed in this commit:
https://github.com/vaadin-component-factory/vcf-dark-mode-switch/commit/c0c7794849a7a116ef4410573a12dbdea16ef2a5
